### ISSUE TITLE
🤳📱 Working on smartphone

### ISSUE THREAD

**Issue by PedroReyes** [Ellpeck/ObsidianSimpleTimeTracker#33] opened 2023-12-18 13:18 UTC
Hello,

Will be this plugin available for mobile?

Right now all we can see is the JSON that is used by the plugin with all the timestamps.

Thanks in advanced.

Best regards,
Pedro Reyes.

**Comment by Ellpeck** [comment] 2023-12-18 13:24
Hi! The plugin already works on mobile:

![Screenshot_20231218-142408](https://github.com/Ellpeck/ObsidianSimpleTimeTracker/assets/5741138/3277296e-bc6f-4a0c-bc47-b44426bdfe3d)

Perhaps you're in reading mode, in which case this is a duplicate of #31!

**Closed by Ellpeck** 2023-12-18 13:24 UTC
